### ISSUE TITLE
Windows Friendly

### ISSUE THREAD

**Issue by nhrones** [kt3k/packup#10]
On Windows, packup outputs 'Server running at http://0.0.0.0:1234'
This should be corrected to read 'Server running at http://localhost:1234' or ...
 'Server running at http://127.0.0.1:1234'
export { serve as serveIterable } from "https://deno.land/x/iterable_file_server@v0.1.7/mod.ts"; returns a listener from Deno.serve.  This is where addr is unconditionally defaulted to "0.0.0.0"
Deno.serve() should use `Deno.Build.os` to return a correct default value.
```js
let addr = (Deno.Build.os === "windows") ? "127.0.0.1" : "0.0.0.0";
```

**Comment by kt3k** [comment]
Changed the message to `Server running at http://localhost:1234`. Thank you for the feedback!

**Comment by nhrones** [comment]
Thank you for the change.
