### ISSUE TITLE
Add Feature/Bug/PR Request/Report templates

### ISSUE THREAD

**Issue by murindwaz** [kt3k/packup#2]
It would be great to have templates stating feature requests, bug reports, and regular pull requests. 
These `git` templates will make it easy to do triage(issues), and prioritize features coming out of the community.

**Comment by kt3k** [comment]
Do you have any recommendation for such templates?

**Comment by murindwaz** [comment]
@kt3k ~ Here are a couple of templates used in some popular projects. This can be a pretty good starting point, then other members can amend the content, as they see fit. 

- https://github.com/angular/angular/tree/master/.github
- https://github.com/gatsbyjs/gatsby/tree/master/.github 
- https://github.com/facebook/create-react-app/tree/master/.github

What do you think?
