### ISSUE TITLE
Doc site improvements

### ISSUE THREAD

**Issue by kt3k** [kt3k/packup#3]
- [x] Fix syntax hightlight
- [x] Fix sidebar
- Organize examples page
  - [x] Simple
  - [x] React + React Router
  - [x] styled-components
  - [ ] tailwind
- [x] CLI commands page in [GETTING STARTED] section
- [x] Type Checking page in [GETTING STARTED] section
- [x] Registries / CDNs page in [GUIDES] section
- [x] Write about static/ directory

https://scrapbox.io/kt3k/packup_docs

**Comment by ikmrgrv** [comment]
@kt3k What do we use for syntax highlighting at present ??
https://highlightjs.org/ is a good library.

**Comment by kt3k** [comment]
I first tried highlight.js, but the syntax highlighting doesn't look good to me.

<img width="1127" alt="スクリーンショット 2021-06-16 13 48 02" src="https://user-images.githubusercontent.com/613956/122159617-891b6180-cea9-11eb-91a4-046268bcb89e.png">

Now I'm considering using readonly mode of monaco-editor. The same example renders like the below:

<img width="884" alt="スクリーンショット 2021-06-16 13 52 46" src="https://user-images.githubusercontent.com/613956/122160039-38f0cf00-ceaa-11eb-8012-92cf645ab0b1.png">

**Comment by kt3k** [comment]
We continue improving the docs, but this issue seems almost done. Closing
