### ISSUE TITLE
keep specified imports without bundled

### ISSUE THREAD

**Issue by mindon** [kt3k/packup#45]
**Is your feature request related to a problem?**
-------
Here's the problem:
**index.html***
```
<script type="module" src="./a.ts"></script>
<script type="module" src="./b.ts"></script>
```
and both inside **a.ts** and **b.ts** there's `imports "./c.ts"`.
`packup build` results the js code of **c.ts** included both in **a.js** and **b.js**.

**Describe the solution you'd like**
-------
intead of bundle everything imports,
could packup supports **// !packup=rules** comment like following?
```
// !bundle=module
import "./c.ts";
```
"// !bundle=module" bundle c.ts as c-###.js and change import to `import "./c-###.js";` in the final result.

```
// !bundle=off
imports "https://demo.com/c.js";
```
"// !bundle=off" keeps the followed imports without changed.

------
btw, could the output of js files keep the name as its name prefix?
it seems named by the html file name right now - if more than one html using the same **m.ts**, there will be more than one copy with different names.

**Comment by mindon** [comment]
here comes my fork without wasm and update deps' versions https://github.com/mindon/packup
```typescript
// usage
// !bundle=off|module or customized directory (start with / as dist root) or name (without suffix /)
// ;

// !bundle=/shared/depends
import { something } from '../deps.ts';
```

this example generate **depends.md5-code.js** under **dist/shared/**, and keeps using
`import { something } from './shared/depends.md5-code.js';`

**Comment by kt3k** [comment]
@mindon Great!
